import os
import sys
import pandas as pd
from numpy import array
from collections import Counter

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../src")
from algorithm import join_data, predict_data, filter_data, text_to_vector, get_cosine, remove_stopwords


def test_join_data():
    news_in_values = [[0,
            'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.'],
        [1,
            "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus."],
        [2,
            'Man Slaps Macron During Visit to Southern France - The  Two people were arrested after a man slapped the French president as he was approaching a small crowd, prompting condemnation of the attack across the political spectrum.'],
        [3,
            'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.'],
        [4,
            "Biogen faces tough questions over $56K-a-year price of newly approved Alzheimer's drug -  Biogen on Tuesday faced tough questions from Wall Street analysts over the $56,000 annual cost of its newly approved Alzheimer's drug, Aduhelm."]]
    news_in_columns = ['news_id', 'news']
    news_df_in = pd.DataFrame(news_in_values, columns = news_in_columns)
    wiki_in_values = [[0, 'Sony (organization)', 'Sony'],
        [0, 'WF-1000XM4', 'List of minor planets: 3001–4000'],
        [0, 'LDAC (organization)', 'Audio coding format'],
        [0, 'IPX4 (organization)', 'OSI model'],
        [1, 'Democrats', 'Democrat'],
        [1, 'Manchin -  ', 'Joe Manchin'],
        [2, 'French', 'French'],
        [3, 'Justice Department (organization)',
            'United States Department of Justice'],
        [3, 'Continues Trump', 'Donald Trump'],
        [3, 'Carroll (organization)', 'Bonnie Carroll']]
    wiki_in_columns = ['news_id', 'entity', 'title']
    wiki_df_in = pd.DataFrame(wiki_in_values, columns = wiki_in_columns)
    joined_in_values = [[0, 0, 'Sony (organization)', 'Sony',
            'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
            'Jun-09-2021'],
        [1, 0, 'WF-1000XM4', 'List of minor planets: 3001–4000',
            'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
            'Jun-09-2021'],
        [2, 0, 'LDAC (organization)', 'Audio coding format',
            'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
            'Jun-09-2021'],
        [3, 0, 'IPX4 (organization)', 'OSI model',
            'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
            'Jun-09-2021'],
        [4, 1, 'Democrats', 'Democrat',
            "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus.",
            'Jun-09-2021'],
        [5, 1, 'Manchin -  ', 'Joe Manchin',
            "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus.",
            'Jun-09-2021'],
        [6, 2, 'French', 'French',
            'Man Slaps Macron During Visit to Southern France - The  Two people were arrested after a man slapped the French president as he was approaching a small crowd, prompting condemnation of the attack across the political spectrum.',
            'Jun-09-2021'],
        [7, 3, 'Justice Department (organization)',
            'United States Department of Justice',
            'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
            'Jun-09-2021'],
        [8, 3, 'Continues Trump', 'Donald Trump',
            'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
            'Jun-09-2021'],
        [9, 3, 'Carroll (organization)', 'Bonnie Carroll',
            'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
            'Jun-09-2021']]
    joined_in_columns = ['wiki_id', 'news_id', 'entity', 'title', 'news', 'date']
    joined_df_true = pd.DataFrame(joined_in_values, columns = joined_in_columns)
    
    joined_df_test = join_data(news_df_in, wiki_df_in)
    pd.testing.assert_frame_equal(joined_df_test, joined_df_true)


def test_predict_data():
    in_values = [["Sony Group Corporation (ソニーグループ株式会社, Sonī Gurūpu kabushiki gaisha,  SOH-nee, commonly known as Sony and stylized as SONY) is a Japanese multinational conglomerate corporation headquartered in Kōnan, Minato, Tokyo. The company operates as one of the world's largest manufacturers of consumer and professional electronic products, the largest video game console company and the largest video game publisher. As Sony Entertainment Inc, it is the largest music company (largest music publisher & second largest record label) and the third largest film studio, as well as one of the most comprehensive media companies, being the largest Japanese media conglomerate by size overtaking the privately held, family-owned Yomiuri Shimbun Holdings, the largest Japanese media conglomerate by revenue.Sony, with its 55 percent market share in the image sensor market, is the largest manufacturer of image sensors, the second largest camera manufacturer, and is among the semiconductor sales leaders. It is the world's largest player in the premium TV market for a television of at least 55 inches (140 centimeters) with a price higher than $2,500 as well as second largest TV brand by market share and, as of 2020, the third largest television manufacturer in the world by annual sales figures.Sony Group Corporation is the holding company of the Sony Group (ソニー・グループ, Sonī Gurūpu), which comprises Sony Corporation, Sony Semiconductor Solutions, Sony Entertainment (Sony Pictures, Sony Music), Sony Interactive Entertainment, Sony Financial Holdings, and others.\nThe company's slogan is Be Moved. Their former slogans were The One and Only (1979–1982), It's a Sony (1982–2005), like.no.other (2005–2009) and make.believe (2009–2013).Sony has a weak tie to the Sumitomo Mitsui Financial Group (SMFG) corporate group, the successor to the Mitsui group. Sony is listed on the Tokyo Stock Exchange (in which it is a constituent of the Nikkei 225 and TOPIX Core30 indexes) with an additional listing in the form of American depositary receipts listed in the New York Stock Exchange (traded since 1970, making it the oldest Japanese company to be listed in an American exchange), and was ranked 122nd on the 2020 Fortune Global 500 list.\n\n\n",
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.'],
       ['The following is a partial list of minor planets, running from minor-planet number 3001 through 4000, inclusive. A detailed description of the table\'s columns and used data sources are given on the main page. The main index provides an overview of the entire minor-planet catalog. Also see the summary list of all named bodies in numerical and alphabetical order, as well as the corresponding naming citations for this number range. Summary statistics and details on the dynamical classification of minor planets can be found on the main page. New namings may only be added to this list after official publication, as the preannouncement of names is condemned by the Committee on Small Body Nomenclature. This article incorporates material from the National Aeronautics and Space Administration document: "Small-Body Orbital Elements (ASCII Files)". Additional data files are provided by the International Astronomical Union\'s Minor Planet Center.',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.'],
       ['An audio coding format (or sometimes audio compression format) is a content representation format for storage or transmission of digital audio (such as in digital television, digital radio and in audio and video files). Examples of audio coding formats include MP3, AAC, Vorbis, FLAC, and Opus. A specific software or hardware implementation capable of audio compression and decompression to/from a specific audio coding format is called an audio codec; an example of an audio codec is LAME, which is one of several different codecs which implements encoding and decoding audio in the MP3 audio coding format in software. \nSome audio coding formats are documented by a detailed technical specification document known as an audio coding specification. Some such specifications are written and approved by standardization organizations as technical standards, and are thus known as an audio coding standard. The term "standard" is also sometimes used for de facto standards as well as formal standards.\nAudio content encoded in a particular audio coding format is normally encapsulated within a container format. As such, the user normally doesn\'t have a raw AAC file, but instead has a .m4a audio file, which is a MPEG-4 Part 14 container containing AAC-encoded audio. The container also contains metadata such as title and other tags, and perhaps an index for fast seeking. A notable exception is MP3 files, which are raw audio coding without a container format.',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.'],
       ['The Open Systems Interconnection model (OSI model) is a conceptual model that characterises and standardises the communication functions of a telecommunication or computing system without regard to its underlying internal structure and technology. Its goal is the interoperability of diverse communication systems with standard communication protocols.\nThe model partitions the flow of data in a communication system into seven abstraction layers, from the physical implementation of transmitting bits across a communications medium to the highest-level representation of data of a distributed application. Each intermediate layer serves a class of functionality to the layer above it and is served by the layer below it. Classes of functionality are realized in software by standardized communication protocols.\nThe OSI model was developed starting in the late 1970s to support the emergence of the diverse computer networking methods that were competing for application in the large national networking efforts in France, the United Kingdom, and the United States. In the 1980s, the model became a working product of the Open Systems Interconnection group at the International Organization for Standardization (ISO). While attempting to provide a comprehensive description of networking, the model failed to garner reliance by the software architects in the design of the early Internet, which is reflected in the less prescriptive Internet Protocol Suite, principally sponsored under the auspices of the Internet Engineering Task Force (IETF).\n\n\n',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.'],
       ['Democrat, Democrats, or Democratic may refer to:\n\nA proponent of democracy, or democratic government; a form of government involving rule by the people.',
        "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus."],
       ['Joseph Manchin III (born August 24, 1947) is an American politician serving as the senior United States senator from West Virginia, a seat he has held since 2010. A member of the Democratic Party, he was the 34th governor of West Virginia from 2005 to 2010 and the 27th secretary of state of West Virginia from 2001 to 2005.\nManchin has called himself a "moderate conservative Democrat" and is often cited as the most conservative Democrat in the Senate. West Virginia has become one of the most heavily Republican states in the country, but Manchin has continued to see electoral success. He won the 2004 gubernatorial election by a large margin and was reelected by an even larger margin in 2008; in both years, Republican presidential candidates won West Virginia. Manchin won the 2010 special election to fill the Senate seat vacated by incumbent Democrat Robert Byrd\'s death with 54% of the vote. He was elected to a full term in 2012 with 61% of the vote and reelected in 2018 with just under 50% of the vote, as the state had become increasingly partisan. He became the state\'s senior U.S. Senator when Jay Rockefeller retired in 2015.\nAs a member of Congress, Manchin is known for his support of bipartisanship, voting or working with Republicans on issues such as abortion and gun ownership. He opposed the energy policies of President Barack Obama, voted against cloture for the Don\'t Ask, Don\'t Tell Repeal Act of 2010 (he did not vote on the bill itself), voted to remove federal funding for Planned Parenthood in 2015, supported President Donald Trump\'s immigration policies and voted to confirm most of his cabinet and judicial appointees, including Associate Justice Brett Kavanaugh.',
        "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus."],
       ['French (French: français(e)) may refer to:\n\nSomething of, from, or related to France\nFrench language, a French language which originated in France, and its various dialects\nFrench people, a nation and ethnic group identified with France\nFrench cuisine, cooking traditions and practices\n\n\n',
        'Man Slaps Macron During Visit to Southern France - The  Two people were arrested after a man slapped the French president as he was approaching a small crowd, prompting condemnation of the attack across the political spectrum.'],
       ['The United States Department of Justice (DOJ), also known as the Justice Department, is a federal executive department of the United States government tasked with  the enforcement of federal law and administration of justice in the United States. It is equivalent to the justice or interior ministries of other countries. The modern incarnation of the department was formed in 1870 during the Ulysses S. Grant presidency. The department is composed of federal law enforcement agencies, including the U.S. Marshals Service, the Federal Bureau of Investigation, the Bureau of Alcohol, Tobacco, Firearms and Explosives, and the Drug Enforcement Administration. The primary actions of the DOJ are investigating instances of white collar crime, representing the U.S. government in legal matters (such as in cases before the Supreme Court), and running the federal prison system. The department is also responsible for reviewing the conduct of local law enforcement as directed by the Violent Crime Control and Law Enforcement Act of 1994.The department is headed by the U.S. Attorney General, who is nominated by the president and confirmed by the US Senate and is a member of the Cabinet. The current attorney general is Merrick Garland, who was sworn in March 11, 2021.\n\n\n',
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.'],
       ["Donald John Trump (born June 14, 1946) is an American media personality and businessman who served as the 45th president of the United States from 2017 to 2021.\nBorn and raised in Queens, New York City, Trump attended Fordham University and the University of Pennsylvania, graduating with a bachelor's degree in 1968. He became the president of his father Fred Trump's real estate business in 1971 and renamed it The Trump Organization. Trump expanded the company's operations to building and renovating skyscrapers, hotels, casinos, and golf courses. He later started various side ventures, mostly by licensing his name. Trump and his businesses have been involved in more than 4,000 state and federal legal actions, including six bankruptcies. He owned the Miss Universe brand of beauty pageants from 1996 to 2015. From 2003 to 2015 he co-produced and hosted the reality television series The Apprentice.\nTrump's political positions have been described as populist, protectionist, isolationist, and nationalist. He entered the 2016 presidential race as a Republican and was elected in an upset victory over Democratic nominee Hillary Clinton while losing the popular vote.",
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.'],
       ['Bonnie Carroll is an American widow who is the president and founder of the Tragedy Assistance Program for Survivors (TAPS), an organization that provides care, welfare and support to people who have lost a loved one to military service. She is the surviving spouse of Army Brig. Gen. Tom Carroll who died in an Army C-12 crash on November 12, 1992. In 2015 she was awarded the Presidential Medal of Freedom.\n\n\n',
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.']]
    in_columns = ['wiki', 'news']
    df_in = pd.DataFrame(in_values, columns = in_columns)

    out_values = [["Sony Group Corporation (ソニーグループ株式会社, Sonī Gurūpu kabushiki gaisha,  SOH-nee, commonly known as Sony and stylized as SONY) is a Japanese multinational conglomerate corporation headquartered in Kōnan, Minato, Tokyo. The company operates as one of the world's largest manufacturers of consumer and professional electronic products, the largest video game console company and the largest video game publisher. As Sony Entertainment Inc, it is the largest music company (largest music publisher & second largest record label) and the third largest film studio, as well as one of the most comprehensive media companies, being the largest Japanese media conglomerate by size overtaking the privately held, family-owned Yomiuri Shimbun Holdings, the largest Japanese media conglomerate by revenue.Sony, with its 55 percent market share in the image sensor market, is the largest manufacturer of image sensors, the second largest camera manufacturer, and is among the semiconductor sales leaders. It is the world's largest player in the premium TV market for a television of at least 55 inches (140 centimeters) with a price higher than $2,500 as well as second largest TV brand by market share and, as of 2020, the third largest television manufacturer in the world by annual sales figures.Sony Group Corporation is the holding company of the Sony Group (ソニー・グループ, Sonī Gurūpu), which comprises Sony Corporation, Sony Semiconductor Solutions, Sony Entertainment (Sony Pictures, Sony Music), Sony Interactive Entertainment, Sony Financial Holdings, and others.\nThe company's slogan is Be Moved. Their former slogans were The One and Only (1979–1982), It's a Sony (1982–2005), like.no.other (2005–2009) and make.believe (2009–2013).Sony has a weak tie to the Sumitomo Mitsui Financial Group (SMFG) corporate group, the successor to the Mitsui group. Sony is listed on the Tokyo Stock Exchange (in which it is a constituent of the Nikkei 225 and TOPIX Core30 indexes) with an additional listing in the form of American depositary receipts listed in the New York Stock Exchange (traded since 1970, making it the oldest Japanese company to be listed in an American exchange), and was ranked 122nd on the 2020 Fortune Global 500 list.\n\n\n",
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        "sony group corporation (ソニーグループ株式会社, sonī gurūpu kabushiki gaisha, soh-nee, commonly known sony stylized sony) japanese multinational conglomerate corporation headquartered kōnan, minato, tokyo. company operates one world's largest manufacturers consumer professional electronic products, largest video game console company largest video game publisher. sony entertainment inc, largest music company (largest music publisher & second largest record label) third largest film studio, well one comprehensive media companies, largest japanese media conglomerate size overtaking privately held, family-owned yomiuri shimbun holdings, largest japanese media conglomerate revenue.sony, 55 percent market share image sensor market, largest manufacturer image sensors, second largest camera manufacturer, among semiconductor sales leaders. world's largest player premium tv market television least 55 inches (140 centimeters) price higher $2,500 well second largest tv brand market share and, 2020, third largest television manufacturer world annual sales figures.sony group corporation holding company sony group (ソニー・グループ, sonī gurūpu), comprises sony corporation, sony semiconductor solutions, sony entertainment (sony pictures, sony music), sony interactive entertainment, sony financial holdings, others. company's slogan moved. former slogans one (1979–1982), sony (1982–2005), like.no.other (2005–2009) make.believe (2009–2013).sony weak tie sumitomo mitsui financial group (smfg) corporate group, successor mitsui group. sony listed tokyo stock exchange (in constituent nikkei 225 topix core30 indexes) additional listing form american depositary receipts listed new york stock exchange (traded since 1970, making oldest japanese company listed american exchange), ranked 122nd 2020 fortune global 500 list.",
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.16712542521861243, False],
       ['The following is a partial list of minor planets, running from minor-planet number 3001 through 4000, inclusive. A detailed description of the table\'s columns and used data sources are given on the main page. The main index provides an overview of the entire minor-planet catalog. Also see the summary list of all named bodies in numerical and alphabetical order, as well as the corresponding naming citations for this number range. Summary statistics and details on the dynamical classification of minor planets can be found on the main page. New namings may only be added to this list after official publication, as the preannouncement of names is condemned by the Committee on Small Body Nomenclature. This article incorporates material from the National Aeronautics and Space Administration document: "Small-Body Orbital Elements (ASCII Files)". Additional data files are provided by the International Astronomical Union\'s Minor Planet Center.',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        'following partial list minor planets, running minor-planet number 3001 4000, inclusive. detailed description table\'s columns used data sources given main page. main index provides overview entire minor-planet catalog. also see summary list named bodies numerical alphabetical order, well corresponding naming citations number range. summary statistics details dynamical classification minor planets found main page. new namings may added list official publication, preannouncement names condemned committee small body nomenclature. article incorporates material national aeronautics space administration document: "small-body orbital elements (ascii files)". additional data files provided international astronomical union\'s minor planet center.',
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.03233667436345479, False],
       ['An audio coding format (or sometimes audio compression format) is a content representation format for storage or transmission of digital audio (such as in digital television, digital radio and in audio and video files). Examples of audio coding formats include MP3, AAC, Vorbis, FLAC, and Opus. A specific software or hardware implementation capable of audio compression and decompression to/from a specific audio coding format is called an audio codec; an example of an audio codec is LAME, which is one of several different codecs which implements encoding and decoding audio in the MP3 audio coding format in software. \nSome audio coding formats are documented by a detailed technical specification document known as an audio coding specification. Some such specifications are written and approved by standardization organizations as technical standards, and are thus known as an audio coding standard. The term "standard" is also sometimes used for de facto standards as well as formal standards.\nAudio content encoded in a particular audio coding format is normally encapsulated within a container format. As such, the user normally doesn\'t have a raw AAC file, but instead has a .m4a audio file, which is a MPEG-4 Part 14 container containing AAC-encoded audio. The container also contains metadata such as title and other tags, and perhaps an index for fast seeking. A notable exception is MP3 files, which are raw audio coding without a container format.',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        'audio coding format (or sometimes audio compression format) content representation format storage transmission digital audio (such digital television, digital radio audio video files). examples audio coding formats include mp3, aac, vorbis, flac, opus. specific software hardware implementation capable audio compression decompression to/from specific audio coding format called audio codec; example audio codec lame, one several different codecs implements encoding decoding audio mp3 audio coding format software. audio coding formats documented detailed technical specification document known audio coding specification. specifications written approved standardization organizations technical standards, thus known audio coding standard. term "standard" also sometimes used de facto standards well formal standards. audio content encoded particular audio coding format normally encapsulated within container format. such, user normally raw aac file, instead .m4a audio file, mpeg-4 part 14 container containing aac-encoded audio. container also contains metadata title tags, perhaps index fast seeking. notable exception mp3 files, raw audio coding without container format.',
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.0, False],
       ['The Open Systems Interconnection model (OSI model) is a conceptual model that characterises and standardises the communication functions of a telecommunication or computing system without regard to its underlying internal structure and technology. Its goal is the interoperability of diverse communication systems with standard communication protocols.\nThe model partitions the flow of data in a communication system into seven abstraction layers, from the physical implementation of transmitting bits across a communications medium to the highest-level representation of data of a distributed application. Each intermediate layer serves a class of functionality to the layer above it and is served by the layer below it. Classes of functionality are realized in software by standardized communication protocols.\nThe OSI model was developed starting in the late 1970s to support the emergence of the diverse computer networking methods that were competing for application in the large national networking efforts in France, the United Kingdom, and the United States. In the 1980s, the model became a working product of the Open Systems Interconnection group at the International Organization for Standardization (ISO). While attempting to provide a comprehensive description of networking, the model failed to garner reliance by the software architects in the design of the early Internet, which is reflected in the less prescriptive Internet Protocol Suite, principally sponsored under the auspices of the Internet Engineering Task Force (IETF).\n\n\n',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        'open systems interconnection model (osi model) conceptual model characterises standardises communication functions telecommunication computing system without regard underlying internal structure technology. goal interoperability diverse communication systems standard communication protocols. model partitions flow data communication system seven abstraction layers, physical implementation transmitting bits across communications medium highest-level representation data distributed application. intermediate layer serves class functionality layer served layer it. classes functionality realized software standardized communication protocols. osi model developed starting late 1970s support emergence diverse computer networking methods competing application large national networking efforts france, united kingdom, united states. 1980s, model became working product open systems interconnection group international organization standardization (iso). attempting provide comprehensive description networking, model failed garner reliance software architects design early internet, reflected less prescriptive internet protocol suite, principally sponsored auspices internet engineering task force (ietf).',
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.008567687581747002, False],
       ['Democrat, Democrats, or Democratic may refer to:\n\nA proponent of democracy, or democratic government; a form of government involving rule by the people.',
        "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus.",
        'democrat, democrats, democratic may refer to: proponent democracy, democratic government; form government involving rule people.',
        "pelosi urges democrats continue voting rights push, despite manchin - manchin infuriated democrats saying would support party's sweeping voting rights bill, speaker implored party shift focus.",
        0.07647191129018724, False],
       ['Joseph Manchin III (born August 24, 1947) is an American politician serving as the senior United States senator from West Virginia, a seat he has held since 2010. A member of the Democratic Party, he was the 34th governor of West Virginia from 2005 to 2010 and the 27th secretary of state of West Virginia from 2001 to 2005.\nManchin has called himself a "moderate conservative Democrat" and is often cited as the most conservative Democrat in the Senate. West Virginia has become one of the most heavily Republican states in the country, but Manchin has continued to see electoral success. He won the 2004 gubernatorial election by a large margin and was reelected by an even larger margin in 2008; in both years, Republican presidential candidates won West Virginia. Manchin won the 2010 special election to fill the Senate seat vacated by incumbent Democrat Robert Byrd\'s death with 54% of the vote. He was elected to a full term in 2012 with 61% of the vote and reelected in 2018 with just under 50% of the vote, as the state had become increasingly partisan. He became the state\'s senior U.S. Senator when Jay Rockefeller retired in 2015.\nAs a member of Congress, Manchin is known for his support of bipartisanship, voting or working with Republicans on issues such as abortion and gun ownership. He opposed the energy policies of President Barack Obama, voted against cloture for the Don\'t Ask, Don\'t Tell Repeal Act of 2010 (he did not vote on the bill itself), voted to remove federal funding for Planned Parenthood in 2015, supported President Donald Trump\'s immigration policies and voted to confirm most of his cabinet and judicial appointees, including Associate Justice Brett Kavanaugh.',
        "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus.",
        'joseph manchin iii (born august 24, 1947) american politician serving senior united states senator west virginia, seat held since 2010. member democratic party, 34th governor west virginia 2005 2010 27th secretary state west virginia 2001 2005. manchin called "moderate conservative democrat" often cited conservative democrat senate. west virginia become one heavily republican states country, manchin continued see electoral success. 2004 gubernatorial election large margin reelected even larger margin 2008; years, republican presidential candidates west virginia. manchin 2010 special election fill senate seat vacated incumbent democrat robert byrd\'s death 54% vote. elected full term 2012 61% vote reelected 2018 50% vote, state become increasingly partisan. became state\'s senior u.s. senator jay rockefeller retired 2015. member congress, manchin known support bipartisanship, voting working republicans issues abortion gun ownership. opposed energy policies president barack obama, voted cloture ask, tell repeal act 2010 (he vote bill itself), voted remove federal funding planned parenthood 2015, supported president donald trump\'s immigration policies voted confirm cabinet judicial appointees, including associate justice brett kavanaugh.',
        "pelosi urges democrats continue voting rights push, despite manchin - manchin infuriated democrats saying would support party's sweeping voting rights bill, speaker implored party shift focus.",
        0.18751465015433733, False],
       ['French (French: français(e)) may refer to:\n\nSomething of, from, or related to France\nFrench language, a French language which originated in France, and its various dialects\nFrench people, a nation and ethnic group identified with France\nFrench cuisine, cooking traditions and practices\n\n\n',
        'Man Slaps Macron During Visit to Southern France - The  Two people were arrested after a man slapped the French president as he was approaching a small crowd, prompting condemnation of the attack across the political spectrum.',
        'french (french: français(e)) may refer to: something of, from, related france french language, french language originated france, various dialects french people, nation ethnic group identified france french cuisine, cooking traditions practices',
        'man slaps macron visit southern france - two people arrested man slapped french president approaching small crowd, prompting condemnation attack across political spectrum.',
        0.2439750182371333, False],
       ['The United States Department of Justice (DOJ), also known as the Justice Department, is a federal executive department of the United States government tasked with  the enforcement of federal law and administration of justice in the United States. It is equivalent to the justice or interior ministries of other countries. The modern incarnation of the department was formed in 1870 during the Ulysses S. Grant presidency. The department is composed of federal law enforcement agencies, including the U.S. Marshals Service, the Federal Bureau of Investigation, the Bureau of Alcohol, Tobacco, Firearms and Explosives, and the Drug Enforcement Administration. The primary actions of the DOJ are investigating instances of white collar crime, representing the U.S. government in legal matters (such as in cases before the Supreme Court), and running the federal prison system. The department is also responsible for reviewing the conduct of local law enforcement as directed by the Violent Crime Control and Law Enforcement Act of 1994.The department is headed by the U.S. Attorney General, who is nominated by the president and confirmed by the US Senate and is a member of the Cabinet. The current attorney general is Merrick Garland, who was sworn in March 11, 2021.\n\n\n',
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        'united states department justice (doj), also known justice department, federal executive department united states government tasked enforcement federal law administration justice united states. equivalent justice interior ministries countries. modern incarnation department formed 1870 ulysses s. grant presidency. department composed federal law enforcement agencies, including u.s. marshals service, federal bureau investigation, bureau alcohol, tobacco, firearms explosives, drug enforcement administration. primary actions doj investigating instances white collar crime, representing u.s. government legal matters (such cases supreme court), running federal prison system. department also responsible reviewing conduct local law enforcement directed violent crime control law enforcement act 1994.the department headed u.s. attorney general, nominated president confirmed us senate member cabinet. current attorney general merrick garland, sworn march 11, 2021.',
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.',
        0.2504739340746935, True],
       ["Donald John Trump (born June 14, 1946) is an American media personality and businessman who served as the 45th president of the United States from 2017 to 2021.\nBorn and raised in Queens, New York City, Trump attended Fordham University and the University of Pennsylvania, graduating with a bachelor's degree in 1968. He became the president of his father Fred Trump's real estate business in 1971 and renamed it The Trump Organization. Trump expanded the company's operations to building and renovating skyscrapers, hotels, casinos, and golf courses. He later started various side ventures, mostly by licensing his name. Trump and his businesses have been involved in more than 4,000 state and federal legal actions, including six bankruptcies. He owned the Miss Universe brand of beauty pageants from 1996 to 2015. From 2003 to 2015 he co-produced and hosted the reality television series The Apprentice.\nTrump's political positions have been described as populist, protectionist, isolationist, and nationalist. He entered the 2016 presidential race as a Republican and was elected in an upset victory over Democratic nominee Hillary Clinton while losing the popular vote.",
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        "donald john trump (born june 14, 1946) american media personality businessman served 45th president united states 2017 2021. born raised queens, new york city, trump attended fordham university university pennsylvania, graduating bachelor's degree 1968. became president father fred trump's real estate business 1971 renamed trump organization. trump expanded company's operations building renovating skyscrapers, hotels, casinos, golf courses. later started various side ventures, mostly licensing name. trump businesses involved 4,000 state federal legal actions, including six bankruptcies. owned miss universe brand beauty pageants 1996 2015. 2003 2015 co-produced hosted reality television series apprentice. trump's political positions described populist, protectionist, isolationist, nationalist. entered 2016 presidential race republican elected upset victory democratic nominee hillary clinton losing popular vote.",
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.',
        0.22570570137850118, False],
       ['Bonnie Carroll is an American widow who is the president and founder of the Tragedy Assistance Program for Survivors (TAPS), an organization that provides care, welfare and support to people who have lost a loved one to military service. She is the surviving spouse of Army Brig. Gen. Tom Carroll who died in an Army C-12 crash on November 12, 1992. In 2015 she was awarded the Presidential Medal of Freedom.\n\n\n',
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        'bonnie carroll american widow president founder tragedy assistance program survivors (taps), organization provides care, welfare support people lost loved one military service. surviving spouse army brig. gen. tom carroll died army c-12 crash november 12, 1992. 2015 awarded presidential medal freedom.',
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.',
        0.12961896184130317, False]]
    out_columns = ['wiki', 'news', 'wiki_process', 'news_process', 'sim', 'predict']
    true_out = pd.DataFrame(out_values, columns=out_columns)

    conf = {'threshhold': 0.25,
            'raw_features': ['wiki', 'news'],
            'processed_features': ['wiki_process', 'news_process']}
    test_out = predict_data(df_in, conf)

    
    pd.testing.assert_frame_equal(test_out, true_out)


def test_filter_data():
    in_values = [[0, 'Sony',
        "Sony Group Corporation (ソニーグループ株式会社, Sonī Gurūpu kabushiki gaisha,  SOH-nee, commonly known as Sony and stylized as SONY) is a Japanese multinational conglomerate corporation headquartered in Kōnan, Minato, Tokyo. The company operates as one of the world's largest manufacturers of consumer and professional electronic products, the largest video game console company and the largest video game publisher. As Sony Entertainment Inc, it is the largest music company (largest music publisher & second largest record label) and the third largest film studio, as well as one of the most comprehensive media companies, being the largest Japanese media conglomerate by size overtaking the privately held, family-owned Yomiuri Shimbun Holdings, the largest Japanese media conglomerate by revenue.Sony, with its 55 percent market share in the image sensor market, is the largest manufacturer of image sensors, the second largest camera manufacturer, and is among the semiconductor sales leaders. It is the world's largest player in the premium TV market for a television of at least 55 inches (140 centimeters) with a price higher than $2,500 as well as second largest TV brand by market share and, as of 2020, the third largest television manufacturer in the world by annual sales figures.Sony Group Corporation is the holding company of the Sony Group (ソニー・グループ, Sonī Gurūpu), which comprises Sony Corporation, Sony Semiconductor Solutions, Sony Entertainment (Sony Pictures, Sony Music), Sony Interactive Entertainment, Sony Financial Holdings, and others.\nThe company's slogan is Be Moved. Their former slogans were The One and Only (1979–1982), It's a Sony (1982–2005), like.no.other (2005–2009) and make.believe (2009–2013).Sony has a weak tie to the Sumitomo Mitsui Financial Group (SMFG) corporate group, the successor to the Mitsui group. Sony is listed on the Tokyo Stock Exchange (in which it is a constituent of the Nikkei 225 and TOPIX Core30 indexes) with an additional listing in the form of American depositary receipts listed in the New York Stock Exchange (traded since 1970, making it the oldest Japanese company to be listed in an American exchange), and was ranked 122nd on the 2020 Fortune Global 500 list.\n\n\n",
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        "sony group corporation (ソニーグループ株式会社, sonī gurūpu kabushiki gaisha, soh-nee, commonly known sony stylized sony) japanese multinational conglomerate corporation headquartered kōnan, minato, tokyo. company operates one world's largest manufacturers consumer professional electronic products, largest video game console company largest video game publisher. sony entertainment inc, largest music company (largest music publisher & second largest record label) third largest film studio, well one comprehensive media companies, largest japanese media conglomerate size overtaking privately held, family-owned yomiuri shimbun holdings, largest japanese media conglomerate revenue.sony, 55 percent market share image sensor market, largest manufacturer image sensors, second largest camera manufacturer, among semiconductor sales leaders. world's largest player premium tv market television least 55 inches (140 centimeters) price higher $2,500 well second largest tv brand market share and, 2020, third largest television manufacturer world annual sales figures.sony group corporation holding company sony group (ソニー・グループ, sonī gurūpu), comprises sony corporation, sony semiconductor solutions, sony entertainment (sony pictures, sony music), sony interactive entertainment, sony financial holdings, others. company's slogan moved. former slogans one (1979–1982), sony (1982–2005), like.no.other (2005–2009) make.believe (2009–2013).sony weak tie sumitomo mitsui financial group (smfg) corporate group, successor mitsui group. sony listed tokyo stock exchange (in constituent nikkei 225 topix core30 indexes) additional listing form american depositary receipts listed new york stock exchange (traded since 1970, making oldest japanese company listed american exchange), ranked 122nd 2020 fortune global 500 list.",
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.16712542521861243, False],
       [0, 'List of minor planets: 3001–4000',
        'The following is a partial list of minor planets, running from minor-planet number 3001 through 4000, inclusive. A detailed description of the table\'s columns and used data sources are given on the main page. The main index provides an overview of the entire minor-planet catalog. Also see the summary list of all named bodies in numerical and alphabetical order, as well as the corresponding naming citations for this number range. Summary statistics and details on the dynamical classification of minor planets can be found on the main page. New namings may only be added to this list after official publication, as the preannouncement of names is condemned by the Committee on Small Body Nomenclature. This article incorporates material from the National Aeronautics and Space Administration document: "Small-Body Orbital Elements (ASCII Files)". Additional data files are provided by the International Astronomical Union\'s Minor Planet Center.',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        'following partial list minor planets, running minor-planet number 3001 4000, inclusive. detailed description table\'s columns used data sources given main page. main index provides overview entire minor-planet catalog. also see summary list named bodies numerical alphabetical order, well corresponding naming citations number range. summary statistics details dynamical classification minor planets found main page. new namings may added list official publication, preannouncement names condemned committee small body nomenclature. article incorporates material national aeronautics space administration document: "small-body orbital elements (ascii files)". additional data files provided international astronomical union\'s minor planet center.',
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.03233667436345479, False],
       [0, 'Audio coding format',
        'An audio coding format (or sometimes audio compression format) is a content representation format for storage or transmission of digital audio (such as in digital television, digital radio and in audio and video files). Examples of audio coding formats include MP3, AAC, Vorbis, FLAC, and Opus. A specific software or hardware implementation capable of audio compression and decompression to/from a specific audio coding format is called an audio codec; an example of an audio codec is LAME, which is one of several different codecs which implements encoding and decoding audio in the MP3 audio coding format in software. \nSome audio coding formats are documented by a detailed technical specification document known as an audio coding specification. Some such specifications are written and approved by standardization organizations as technical standards, and are thus known as an audio coding standard. The term "standard" is also sometimes used for de facto standards as well as formal standards.\nAudio content encoded in a particular audio coding format is normally encapsulated within a container format. As such, the user normally doesn\'t have a raw AAC file, but instead has a .m4a audio file, which is a MPEG-4 Part 14 container containing AAC-encoded audio. The container also contains metadata such as title and other tags, and perhaps an index for fast seeking. A notable exception is MP3 files, which are raw audio coding without a container format.',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        'audio coding format (or sometimes audio compression format) content representation format storage transmission digital audio (such digital television, digital radio audio video files). examples audio coding formats include mp3, aac, vorbis, flac, opus. specific software hardware implementation capable audio compression decompression to/from specific audio coding format called audio codec; example audio codec lame, one several different codecs implements encoding decoding audio mp3 audio coding format software. audio coding formats documented detailed technical specification document known audio coding specification. specifications written approved standardization organizations technical standards, thus known audio coding standard. term "standard" also sometimes used de facto standards well formal standards. audio content encoded particular audio coding format normally encapsulated within container format. such, user normally raw aac file, instead .m4a audio file, mpeg-4 part 14 container containing aac-encoded audio. container also contains metadata title tags, perhaps index fast seeking. notable exception mp3 files, raw audio coding without container format.',
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.0, False],
       [0, 'OSI model',
        'The Open Systems Interconnection model (OSI model) is a conceptual model that characterises and standardises the communication functions of a telecommunication or computing system without regard to its underlying internal structure and technology. Its goal is the interoperability of diverse communication systems with standard communication protocols.\nThe model partitions the flow of data in a communication system into seven abstraction layers, from the physical implementation of transmitting bits across a communications medium to the highest-level representation of data of a distributed application. Each intermediate layer serves a class of functionality to the layer above it and is served by the layer below it. Classes of functionality are realized in software by standardized communication protocols.\nThe OSI model was developed starting in the late 1970s to support the emergence of the diverse computer networking methods that were competing for application in the large national networking efforts in France, the United Kingdom, and the United States. In the 1980s, the model became a working product of the Open Systems Interconnection group at the International Organization for Standardization (ISO). While attempting to provide a comprehensive description of networking, the model failed to garner reliance by the software architects in the design of the early Internet, which is reflected in the less prescriptive Internet Protocol Suite, principally sponsored under the auspices of the Internet Engineering Task Force (IETF).\n\n\n',
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        'open systems interconnection model (osi model) conceptual model characterises standardises communication functions telecommunication computing system without regard underlying internal structure technology. goal interoperability diverse communication systems standard communication protocols. model partitions flow data communication system seven abstraction layers, physical implementation transmitting bits across communications medium highest-level representation data distributed application. intermediate layer serves class functionality layer served layer it. classes functionality realized software standardized communication protocols. osi model developed starting late 1970s support emergence diverse computer networking methods competing application large national networking efforts france, united kingdom, united states. 1980s, model became working product open systems interconnection group international organization standardization (iso). attempting provide comprehensive description networking, model failed garner reliance software architects design early internet, reflected less prescriptive internet protocol suite, principally sponsored auspices internet engineering task force (ietf).',
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.',
        0.008567687581747002, False],
       [1, 'Democrat',
        'Democrat, Democrats, or Democratic may refer to:\n\nA proponent of democracy, or democratic government; a form of government involving rule by the people.',
        "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus.",
        'democrat, democrats, democratic may refer to: proponent democracy, democratic government; form government involving rule people.',
        "pelosi urges democrats continue voting rights push, despite manchin - manchin infuriated democrats saying would support party's sweeping voting rights bill, speaker implored party shift focus.",
        0.07647191129018724, False],
       [1, 'Joe Manchin',
        'Joseph Manchin III (born August 24, 1947) is an American politician serving as the senior United States senator from West Virginia, a seat he has held since 2010. A member of the Democratic Party, he was the 34th governor of West Virginia from 2005 to 2010 and the 27th secretary of state of West Virginia from 2001 to 2005.\nManchin has called himself a "moderate conservative Democrat" and is often cited as the most conservative Democrat in the Senate. West Virginia has become one of the most heavily Republican states in the country, but Manchin has continued to see electoral success. He won the 2004 gubernatorial election by a large margin and was reelected by an even larger margin in 2008; in both years, Republican presidential candidates won West Virginia. Manchin won the 2010 special election to fill the Senate seat vacated by incumbent Democrat Robert Byrd\'s death with 54% of the vote. He was elected to a full term in 2012 with 61% of the vote and reelected in 2018 with just under 50% of the vote, as the state had become increasingly partisan. He became the state\'s senior U.S. Senator when Jay Rockefeller retired in 2015.\nAs a member of Congress, Manchin is known for his support of bipartisanship, voting or working with Republicans on issues such as abortion and gun ownership. He opposed the energy policies of President Barack Obama, voted against cloture for the Don\'t Ask, Don\'t Tell Repeal Act of 2010 (he did not vote on the bill itself), voted to remove federal funding for Planned Parenthood in 2015, supported President Donald Trump\'s immigration policies and voted to confirm most of his cabinet and judicial appointees, including Associate Justice Brett Kavanaugh.',
        "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus.",
        'joseph manchin iii (born august 24, 1947) american politician serving senior united states senator west virginia, seat held since 2010. member democratic party, 34th governor west virginia 2005 2010 27th secretary state west virginia 2001 2005. manchin called "moderate conservative democrat" often cited conservative democrat senate. west virginia become one heavily republican states country, manchin continued see electoral success. 2004 gubernatorial election large margin reelected even larger margin 2008; years, republican presidential candidates west virginia. manchin 2010 special election fill senate seat vacated incumbent democrat robert byrd\'s death 54% vote. elected full term 2012 61% vote reelected 2018 50% vote, state become increasingly partisan. became state\'s senior u.s. senator jay rockefeller retired 2015. member congress, manchin known support bipartisanship, voting working republicans issues abortion gun ownership. opposed energy policies president barack obama, voted cloture ask, tell repeal act 2010 (he vote bill itself), voted remove federal funding planned parenthood 2015, supported president donald trump\'s immigration policies voted confirm cabinet judicial appointees, including associate justice brett kavanaugh.',
        "pelosi urges democrats continue voting rights push, despite manchin - manchin infuriated democrats saying would support party's sweeping voting rights bill, speaker implored party shift focus.",
        0.18751465015433733, False],
       [2, 'French',
        'French (French: français(e)) may refer to:\n\nSomething of, from, or related to France\nFrench language, a French language which originated in France, and its various dialects\nFrench people, a nation and ethnic group identified with France\nFrench cuisine, cooking traditions and practices\n\n\n',
        'Man Slaps Macron During Visit to Southern France - The  Two people were arrested after a man slapped the French president as he was approaching a small crowd, prompting condemnation of the attack across the political spectrum.',
        'french (french: français(e)) may refer to: something of, from, related france french language, french language originated france, various dialects french people, nation ethnic group identified france french cuisine, cooking traditions practices',
        'man slaps macron visit southern france - two people arrested man slapped french president approaching small crowd, prompting condemnation attack across political spectrum.',
        0.2439750182371333, False],
       [3, 'United States Department of Justice',
        'The United States Department of Justice (DOJ), also known as the Justice Department, is a federal executive department of the United States government tasked with  the enforcement of federal law and administration of justice in the United States. It is equivalent to the justice or interior ministries of other countries. The modern incarnation of the department was formed in 1870 during the Ulysses S. Grant presidency. The department is composed of federal law enforcement agencies, including the U.S. Marshals Service, the Federal Bureau of Investigation, the Bureau of Alcohol, Tobacco, Firearms and Explosives, and the Drug Enforcement Administration. The primary actions of the DOJ are investigating instances of white collar crime, representing the U.S. government in legal matters (such as in cases before the Supreme Court), and running the federal prison system. The department is also responsible for reviewing the conduct of local law enforcement as directed by the Violent Crime Control and Law Enforcement Act of 1994.The department is headed by the U.S. Attorney General, who is nominated by the president and confirmed by the US Senate and is a member of the Cabinet. The current attorney general is Merrick Garland, who was sworn in March 11, 2021.\n\n\n',
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        'united states department justice (doj), also known justice department, federal executive department united states government tasked enforcement federal law administration justice united states. equivalent justice interior ministries countries. modern incarnation department formed 1870 ulysses s. grant presidency. department composed federal law enforcement agencies, including u.s. marshals service, federal bureau investigation, bureau alcohol, tobacco, firearms explosives, drug enforcement administration. primary actions doj investigating instances white collar crime, representing u.s. government legal matters (such cases supreme court), running federal prison system. department also responsible reviewing conduct local law enforcement directed violent crime control law enforcement act 1994.the department headed u.s. attorney general, nominated president confirmed us senate member cabinet. current attorney general merrick garland, sworn march 11, 2021.',
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.',
        0.2504739340746935, True],
       [3, 'Donald Trump',
        "Donald John Trump (born June 14, 1946) is an American media personality and businessman who served as the 45th president of the United States from 2017 to 2021.\nBorn and raised in Queens, New York City, Trump attended Fordham University and the University of Pennsylvania, graduating with a bachelor's degree in 1968. He became the president of his father Fred Trump's real estate business in 1971 and renamed it The Trump Organization. Trump expanded the company's operations to building and renovating skyscrapers, hotels, casinos, and golf courses. He later started various side ventures, mostly by licensing his name. Trump and his businesses have been involved in more than 4,000 state and federal legal actions, including six bankruptcies. He owned the Miss Universe brand of beauty pageants from 1996 to 2015. From 2003 to 2015 he co-produced and hosted the reality television series The Apprentice.\nTrump's political positions have been described as populist, protectionist, isolationist, and nationalist. He entered the 2016 presidential race as a Republican and was elected in an upset victory over Democratic nominee Hillary Clinton while losing the popular vote.",
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        "donald john trump (born june 14, 1946) american media personality businessman served 45th president united states 2017 2021. born raised queens, new york city, trump attended fordham university university pennsylvania, graduating bachelor's degree 1968. became president father fred trump's real estate business 1971 renamed trump organization. trump expanded company's operations building renovating skyscrapers, hotels, casinos, golf courses. later started various side ventures, mostly licensing name. trump businesses involved 4,000 state federal legal actions, including six bankruptcies. owned miss universe brand beauty pageants 1996 2015. 2003 2015 co-produced hosted reality television series apprentice. trump's political positions described populist, protectionist, isolationist, nationalist. entered 2016 presidential race republican elected upset victory democratic nominee hillary clinton losing popular vote.",
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.',
        0.22570570137850118, False],
       [3, 'Bonnie Carroll',
        'Bonnie Carroll is an American widow who is the president and founder of the Tragedy Assistance Program for Survivors (TAPS), an organization that provides care, welfare and support to people who have lost a loved one to military service. She is the surviving spouse of Army Brig. Gen. Tom Carroll who died in an Army C-12 crash on November 12, 1992. In 2015 she was awarded the Presidential Medal of Freedom.\n\n\n',
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        'bonnie carroll american widow president founder tragedy assistance program survivors (taps), organization provides care, welfare support people lost loved one military service. surviving spouse army brig. gen. tom carroll died army c-12 crash november 12, 1992. 2015 awarded presidential medal freedom.',
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.',
        0.12961896184130317, False]]
    in_columns = ['news_id', 'title', 'wiki', 'news', 'wiki_process', 'news_process',
       'sim', 'predict']
    in_df = pd.DataFrame(in_values, columns=in_columns)
    test_out = filter_data(in_df)
    
    out_values = [3, 'United States Department of Justice',
        'The United States Department of Justice (DOJ), also known as the Justice Department, is a federal executive department of the United States government tasked with  the enforcement of federal law and administration of justice in the United States. It is equivalent to the justice or interior ministries of other countries. The modern incarnation of the department was formed in 1870 during the Ulysses S. Grant presidency. The department is composed of federal law enforcement agencies, including the U.S. Marshals Service, the Federal Bureau of Investigation, the Bureau of Alcohol, Tobacco, Firearms and Explosives, and the Drug Enforcement Administration. The primary actions of the DOJ are investigating instances of white collar crime, representing the U.S. government in legal matters (such as in cases before the Supreme Court), and running the federal prison system. The department is also responsible for reviewing the conduct of local law enforcement as directed by the Violent Crime Control and Law Enforcement Act of 1994.The department is headed by the U.S. Attorney General, who is nominated by the president and confirmed by the US Senate and is a member of the Cabinet. The current attorney general is Merrick Garland, who was sworn in March 11, 2021.\n\n\n',
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        'united states department justice (doj), also known justice department, federal executive department united states government tasked enforcement federal law administration justice united states. equivalent justice interior ministries countries. modern incarnation department formed 1870 ulysses s. grant presidency. department composed federal law enforcement agencies, including u.s. marshals service, federal bureau investigation, bureau alcohol, tobacco, firearms explosives, drug enforcement administration. primary actions doj investigating instances white collar crime, representing u.s. government legal matters (such cases supreme court), running federal prison system. department also responsible reviewing conduct local law enforcement directed violent crime control law enforcement act 1994.the department headed u.s. attorney general, nominated president confirmed us senate member cabinet. current attorney general merrick garland, sworn march 11, 2021.',
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.',
        0.2504739340746935, True]
    out_columns = ['news_id', 'title', 'wiki', 'news', 'wiki_process', 'news_process',
       'sim', 'predict']
    out_index = pd.Int64Index([7], dtype='int64')
    true_out = pd.DataFrame([out_values], columns=out_columns, index=[7])

    pd.testing.assert_frame_equal(test_out, true_out)


def test_text_to_vector():
    in_text = """Prince Harry and Meghan Markle announce birth of new baby - Prince Harry and Meghan Markle announced the birth of their second child on Sunday. The baby's name, Lilibet"""

    test_out = text_to_vector(in_text)

    true_out = Counter({'Prince': 2, 'Harry': 2, 'and': 2, 'Meghan': 2,
        'Markle': 2, 'announce': 1, 'birth': 2,  'of': 2, 'new': 1,
        'baby': 2, 'announced': 1, 'the': 1, 'their': 1, 'second': 1,
        'child': 1, 'on': 1, 'Sunday': 1, 'The': 1, 's': 1, 'name': 1,
        'Lilibet': 1})

    assert test_out == true_out


def test_get_cosine():
    in1 = """GMC just unveiled its $100,000 Hummer EV SUV with 830-horsepower
     that will hit streets in 2023 (GM). The Hummer EV pickup won't be the
     only "supertruck" in GMC's fleet after the automaker unveiled its Hummer
     EV SUV variant on Saturday. It's slated for release in spring 2023."""

    in2 = """"The GMC Hummer EV is both an upcoming off-road luxury electric
         vehicle produced by GMC (simply referred to as Hummer EV; and badged as
         HEV), and its own sub-brand. The Hummer EV line was launched in October
         2020 through a live stream.\nThe Hummer EV sub-brand includes a pickup
         truck (SUT) and a confirmed Sport Utility Vehicle (SUV) that was
         introduced on 3rd of April 2021."""

    test_out = get_cosine([in1, in2])
    assert round(test_out, 5) == 0.40668


def test_remove_stopwords():
    news_in_values = [[0,
            'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.'],
        [1,
            "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus."],
        [2,
            'Man Slaps Macron During Visit to Southern France - The  Two people were arrested after a man slapped the French president as he was approaching a small crowd, prompting condemnation of the attack across the political spectrum.'],
        [3,
            'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.'],
        [4,
            "Biogen faces tough questions over $56K-a-year price of newly approved Alzheimer's drug -  Biogen on Tuesday faced tough questions from Wall Street analysts over the $56,000 annual cost of its newly approved Alzheimer's drug, Aduhelm."]]
    news_in_columns = ['news_id', 'news']
    news_df_in = pd.DataFrame(news_in_values, columns = news_in_columns)

    true_values = [[0,
        'Sony announces WF-1000XM4 noise-canceling earbuds with LDAC and IPX4 water resistance -  The new WF-1000XM4 earbuds improve on Sony’s last noise-canceling earbuds with longer battery life, IPX4 water resistance, and even better sound with support for LDAC.',
        'sony announces wf-1000xm4 noise-canceling earbuds ldac ipx4 water resistance - new wf-1000xm4 earbuds improve sony’s last noise-canceling earbuds longer battery life, ipx4 water resistance, even better sound support ldac.'],
       [1,
        "Pelosi urges Democrats to continue voting rights push, despite Manchin -  After Manchin infuriated Democrats by saying he would not support the party's sweeping voting rights bill, the speaker implored the party not to shift focus.",
        "pelosi urges democrats continue voting rights push, despite manchin - manchin infuriated democrats saying would support party's sweeping voting rights bill, speaker implored party shift focus."],
       [2,
        'Man Slaps Macron During Visit to Southern France - The  Two people were arrested after a man slapped the French president as he was approaching a small crowd, prompting condemnation of the attack across the political spectrum.',
        'man slaps macron visit southern france - two people arrested man slapped french president approaching small crowd, prompting condemnation attack across political spectrum.'],
       [3,
        'Justice Department Continues Trump Defense In E. Jean Carroll Suit -  The Justice Department simultaneously distanced itself from the allegations Carroll has made that former President Donald Trump sexually assaulted her in the 1990s.',
        'justice department continues trump defense e. jean carroll suit - justice department simultaneously distanced allegations carroll made former president donald trump sexually assaulted 1990s.'],
       [4,
        "Biogen faces tough questions over $56K-a-year price of newly approved Alzheimer's drug -  Biogen on Tuesday faced tough questions from Wall Street analysts over the $56,000 annual cost of its newly approved Alzheimer's drug, Aduhelm.",
        "biogen faces tough questions $56k-a-year price newly approved alzheimer's drug - biogen tuesday faced tough questions wall street analysts $56,000 annual cost newly approved alzheimer's drug, aduhelm."]]
    
    true_columns = ['news_id', 'news', 'news_processed']
    true_out = pd.DataFrame(true_values, columns=true_columns)

    test_out = remove_stopwords(news_df_in, {'raw_features': ['news'], 'processed_features': ['news_processed']})

    pd.testing.assert_frame_equal(test_out, true_out)