FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y python3-pip python3-dev git gcc dos2unix g++

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY ./config/stopwords.zip /root/nltk_data/corpora/stopwords.zip

RUN pip3 install --upgrade pip
RUN pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz --user
RUN pip3 install -r requirements.txt

COPY . /app/

EXPOSE 5000
ENTRYPOINT ["make"]